version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/docusaurus"
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "04:00"
      timezone: America/Chicago
  - package-ecosystem: "npm"
      directory: "/examples/react/solana/checkout"
      versioning-strategy: increase
      schedule:
        interval: daily
        time: "04:00"
        timezone: America/Chicago
  - package-ecosystem: "npm"
      directory: "/examples/react/solana/offramp"
      versioning-strategy: increase
      schedule:
        interval: daily
        time: "04:00"
        timezone: America/Chicago
