services:
  - type: web
    name: coinflow-docs
    env: static
    branch: main
    domains:
      - docs.coinflow.cash
    rootDir: docusaurus
    buildCommand: npm ci && npm run build
    staticPublishPath: build
    buildFilter:
      paths:
        - docusaurus/**/*
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: coinflow-blog
    env: static
    branch: main
    domains:
      - blog.coinflow.cash
    rootDir: blog
    buildCommand: npm ci && npm run build
    staticPublishPath: build
    buildFilter:
      paths:
        - blog/**/*
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: react-solana-checkout
    env: static
    branch: main
    rootDir: examples/react/solana/checkout
    buildCommand: npm ci && npm run build
    staticPublishPath: build
    buildFilter:
      paths:
        - examples/react/solana/checkout/**/*
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_ENV
        value: sandbox
      - key: REACT_APP_MERCHANT_ID
        value: coinflow

  - type: web
    name: react-solana-withdraw
    env: static
    branch: main
    rootDir: examples/react/solana/withdraw
    buildCommand: npm ci && npm run build
    staticPublishPath: build
    buildFilter:
      paths:
        - examples/react/solana/withdraw/**/*
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_ENV
        value: sandbox
      - key: REACT_APP_MERCHANT_ID
        value: coinflow

  - type: web
    name: react-near-checkout
    env: static
    branch: main
    rootDir: examples/react/near/checkout
    buildCommand: npm ci && npm run build
    staticPublishPath: build
    buildFilter:
      paths:
        - examples/react/near/checkout/**/*
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_ENV
        value: sandbox
      - key: REACT_APP_MERCHANT_ID
        value: coinflow

  - type: web
    name: react-near-withdraw
    env: static
    branch: main
    rootDir: examples/react/near/withdraw
    buildCommand: npm ci && npm run build
    staticPublishPath: build
    buildFilter:
      paths:
        - examples/react/near/withdraw/**/*
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_ENV
        value: sandbox
      - key: REACT_APP_MERCHANT_ID
        value: coinflow

  - type: web
    name: react-polygon-checkout
    env: static
    branch: main
    rootDir: examples/react/polygon/checkout
    buildCommand: npm ci && npm run build
    staticPublishPath: build
    buildFilter:
      paths:
        - examples/react/polygon/checkout/**/*
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_ENV
        value: sandbox
      - key: REACT_APP_MERCHANT_ID
        value: coinflow
      - key: REACT_APP_WALLET_CONNECT_PROJECT_ID
        value: 2383b9beda863a0b895ff5603b28bd04
      - key: REACT_APP_POLYGON_RPC_URL
        value: https://rpc.ankr.com/polygon_mumbai

  - type: web
    name: react-polygon-withdraw
    env: static
    branch: main
    rootDir: examples/react/polygon/withdraw
    buildCommand: npm ci && npm run build
    staticPublishPath: build
    buildFilter:
      paths:
        - examples/react/polygon/withdraw/**/*
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_ENV
        value: sandbox
      - key: REACT_APP_MERCHANT_ID
        value: coinflow
      - key: REACT_APP_WALLET_CONNECT_PROJECT_ID
        value: 2383b9beda863a0b895ff5603b28bd04

  - type: web
    name: react-eth-withdraw
    env: static
    branch: main
    rootDir: examples/react/eth/withdraw
    buildCommand: npm ci && npm run build
    staticPublishPath: build
    buildFilter:
      paths:
        - examples/react/eth/withdraw/**/*
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_ENV
        value: sandbox
      - key: REACT_APP_MERCHANT_ID
        value: coinflow
      - key: REACT_APP_WALLET_CONNECT_PROJECT_ID
        value: 2383b9beda863a0b895ff5603b28bd04
