name: Angular Solana Checkout

on:
  push:
    branches: [ main ]
    paths:
      - examples/angular/solana/checkout/checkout-app/**
  pull_request:
    paths:
      - examples/angular/solana/checkout/checkout-app/**

  workflow_dispatch:

jobs:
  angular-solana-checkout:
    uses: ./.github/workflows/frontend-build.yml
    with:
      working-directory: ./examples/solana/checkout/checkout-app/
