name: Angular Polygon Checkout

on:
  push:
    branches: [ main ]
    paths:
      - examples/angular/polygon/checkout/checkout-app/**
  pull_request:
    paths:
      - examples/angular/polygon/checkout/checkout-app/**

  workflow_dispatch:

jobs:
  angular-polygon-checkout:
    uses: ./.github/workflows/frontend-build.yml
    with:
      working-directory: ./examples/polygon/checkout/checkout-app/
