name: Angular Solana Withdraw

on:
  push:
    branches: [ main ]
    paths:
      - examples/angular/solana/withdraw/withdraw/**
  pull_request:
    paths:
      - examples/angular/solana/withdraw/withdraw/**

  workflow_dispatch:

jobs:
  angular-solana-withdraw:
    uses: ./.github/workflows/frontend-build.yml
    with:
      working-directory: ./examples/angular/solana/withdraw/withdraw/
