name: Angular ETH Withdraw

on:
  push:
    branches: [ main ]
    paths:
      - examples/angular/eth/withdraw/withdraw/**
  pull_request:
    paths:
      - examples/angular/eth/withdraw/withdraw/**

  workflow_dispatch:

jobs:
  angular-eth-withdraw:
    uses: ./.github/workflows/frontend-build.yml
    with:
      working-directory: ./examples/angular/eth/withdraw/withdraw/
