name: Angular Base Checkout

on:
  push:
    branches: [ main ]
    paths:
      - examples/angular/base/checkout/checkout-app/**
  pull_request:
    paths:
      - examples/angular/base/checkout/**

  workflow_dispatch:

jobs:
  angular-base-checkout:
    uses: ./.github/workflows/frontend-build.yml
    with:
      working-directory: ./examples/angular/base/checkout/checkout-app/
