name: Angular ETH Checkout

on:
  push:
    branches: [ main ]
    paths:
      - examples/angular/eth/checkout/checkout-app/**
  pull_request:
    paths:
      - examples/angular/eth/checkout/checkout-app/**

  workflow_dispatch:

jobs:
  angular-eth-checkout:
    uses: ./.github/workflows/frontend-build.yml
    with:
      working-directory: ./examples/angular/eth/checkout/checkout-app/
