name: Blog

on:
  push:
    branches: [ main ]
    paths:
      - blog/**
  pull_request:
    paths:
      - blog/**

  workflow_dispatch:

jobs:
  docusaurus:
    uses: ./.github/workflows/frontend-build.yml
    with:
      working-directory: ./blog
