name: React Near Withdraw

on:
  push:
    branches: [ main ]
    paths:
      - examples/react/near/withdraw/**
  pull_request:
    paths:
      - examples/react/near/withdraw/**

  workflow_dispatch:

jobs:
  react-near-withdraw:
    uses: ./.github/workflows/frontend-build.yml
    with:
      working-directory: ./examples/react/near/withdraw/
