name: React Base Withdraw

on:
  push:
    branches: [ main ]
    paths:
      - examples/react/base/withdraw/**
  pull_request:
    paths:
      - examples/react/base/withdraw/**

  workflow_dispatch:

jobs:
  react-base-withdraw:
    uses: ./.github/workflows/frontend-build.yml
    with:
      working-directory: ./examples/react/base/withdraw/
