name: React Polygon Checkout

on:
  push:
    branches: [ main ]
    paths:
      - examples/react/polygon/checkout/**
  pull_request:
    paths:
      - examples/react/polygon/checkout/**

  workflow_dispatch:

jobs:
  react-polygon-checkout:
    uses: ./.github/workflows/frontend-build.yml
    with:
      working-directory: ./examples/react/polygon/checkout/
