name: React Eth Withdraw

on:
  push:
    branches: [ main ]
    paths:
      - examples/react/eth/withdraw/**
  pull_request:
    paths:
      - examples/react/eth/withdraw/**

  workflow_dispatch:

jobs:
  react-eth-withdraw:
    uses: ./.github/workflows/frontend-build.yml
    with:
      working-directory: ./examples/react/eth/withdraw/
