name: React Near Checkout

on:
  push:
    branches: [ main ]
    paths:
      - examples/react/near/checkout/**
  pull_request:
    paths:
      - examples/react/near/checkout/**

  workflow_dispatch:

jobs:
  react-near-checkout:
    uses: ./.github/workflows/frontend-build.yml
    with:
      working-directory: ./examples/react/near/checkout/
