name: React Solana Checkout

on:
  push:
    branches: [ main ]
    paths:
      - template/react/**
  pull_request:
    paths:
      - template/react/**

  workflow_dispatch:

jobs:
  docusaurus:
    uses: ./.github/workflows/frontend-build.yml
    with:
      working-directory: ./template/react/
