name: React Solana Checkout

on:
  push:
    branches: [ main ]
    paths:
      - examples/react/solana/checkout/**
  pull_request:
    paths:
      - examples/react/solana/checkout/**

  workflow_dispatch:

jobs:
  docusaurus:
    uses: ./.github/workflows/frontend-build.yml
    with:
      working-directory: ./examples/react/solana/checkout/
