name: React Polygon Withdraw

on:
  push:
    branches: [ main ]
    paths:
      - examples/react/polygon/withdraw/**
  pull_request:
    paths:
      - examples/react/polygon/withdraw/**

  workflow_dispatch:

jobs:
  react-polygon-withdraw:
    uses: ./.github/workflows/frontend-build.yml
    with:
      working-directory: ./examples/react/polygon/withdraw/
