name: React Base Checkout

on:
  push:
    branches: [ main ]
    paths:
      - examples/react/base/checkout/**
  pull_request:
    paths:
      - examples/react/base/checkout/**

  workflow_dispatch:

jobs:
  react-base-checkout:
    uses: ./.github/workflows/frontend-build.yml
    with:
      working-directory: ./examples/react/base/checkout/
