name: React ETH Checkout

on:
  push:
    branches: [ main ]
    paths:
      - examples/react/eth/checkout/**
  pull_request:
    paths:
      - examples/react/eth/checkout/**

  workflow_dispatch:

jobs:
  react-eth-checkout:
    uses: ./.github/workflows/frontend-build.yml
    with:
      working-directory: ./examples/react/eth/checkout/
