name: React Solana Withdraw

on:
  push:
    branches: [ main ]
    paths:
      - examples/react/solana/withdraw/**
  pull_request:
    paths:
      - examples/react/solana/withdraw/**

  workflow_dispatch:

jobs:
  react-solana-withdraw:
    uses: ./.github/workflows/frontend-build.yml
    with:
      working-directory: ./examples/react/solana/withdraw/
